# Generated by Django 5.0.3 on 2024-09-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('problem_number', models.TextField(blank=True, default='')),
                ('timelimit', models.IntegerField(default=1)),
                ('statement', models.TextField(blank=True, default='')),
                ('input_format', models.TextField(blank=True, default='')),
                ('output_format', models.TextField(blank=True, default='')),
                ('hint', models.TextField(blank=True, default='')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_time', models.DateTimeField(auto_now=True, null=True)),
                ('ans_program', models.TextField(blank=True, default='')),
                ('problem_hard', models.ManyToManyField(blank=True, to='outfile.hard')),
                ('problem_tag', models.ManyToManyField(blank=True, to='outfile.tag')),
            ],
        ),
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sample', models.BooleanField(default=False)),
                ('input', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfile.problem')),
            ],
        ),
    ]
